[package]
name = "yrnu"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["cargo"] }
mlua = { version = "0.10.1", features = ["luajit52", "vendored"] }
pnet = "0.35.0"
rpassword = "7.3.1"
rustyline = { version = "15.0.0", features = ["with-file-history"] }
ssh2 = "0.9.4"
tokio = { version = "1.42.0", features = ["macros", "net", "rt-multi-thread"] }

